import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import IconButton from "./components/IconButton/IconButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full grid grid-cols-[auto_1fr]">
        <section id="left-bar" className="bg-blue-500 w-75 px-5">
          <IconButton
            name={"Add app"}
          />
        </section>

        <section className="bg-red-500">
          {children}
        </section>
      </body>
    </html>
  );
}
